# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: install
    init: |
      virtualenv -p python3 venv
      gp sync-done venv
      source venv/bin/activate
      make install
  - name: serve
    init: gp sync-done venv
    command: |
      source venv/bin/activate
      make serve
  - name: git
    init: gp sync-done venv
    command: |
      source venv/bin/activate
      echo "HELP with error 'error: GH007: Your push would publish a private email address.' while pushing
      1. go to 'http://github.com/settings/emails' to find your Primary email address. It looks like: {ID}+{username}@users.noreply.github.com
      2. execute: git config user.email '{ID}+{username}@users.noreply.github.com'
      3. if a commit where already made, use: git commit --amend --reset-author
      4. no PUSH IT UP!"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-preview

# HELP with error 'error: GH007: Your push would publish a private email address.' while pushing
# 1. go to 'http://github.com/settings/emails' to find your Primary email address. It looks like: {ID}+{username}@users.noreply.github.com
# 2. execute: git config user.email "{ID}+{username}@users.noreply.github.com"
# 3. if a commit where already made, use: git commit --amend --reset-author
# (if you made multiple commits, see https://stackoverflow.com/questions/4981126/how-to-amend-several-commits-in-git-to-change-author/25815116#25815116)
# 4. no PUSH IT UP!
