# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: install
    init: |
      virtualenv -p python3 .
      source bin/activate
      make install
  - name: serve
    command: |
      source bin/activate
      make serve
  - name: git
    command: |
      echo "if you have problems with pushing (error: GH007), see .gitpod.yml for help"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-preview


# HELP with error 'error: GH007: Your push would publish a private email address.' while pushing
# 1. go to 'http://github.com/settings/emails' to find your Primary email address. It looks like: {ID}+{username}@users.noreply.github.com
# 2. execute: git config --global user.email "{ID}+{username}@users.noreply.github.com"
# 3. if a commit where already made, use: git commit --amend --reset-author
# 4. no PUSH IT UP!
# (if you made multiple commits, see https://stackoverflow.com/questions/4981126/how-to-amend-several-commits-in-git-to-change-author/25815116#25815116)
